version: "3.8"

services:
    tails_stores_server:
        image: python:3.11.0a5-alpine3.15
        container_name: tails-stores-server-container
        volumes:
            - ./server:/app/server
        working_dir: /app/server
        command: sh -c "pip3 install -r requirements.txt && export FLASK_APP=app && 
            export FLASK_ENV=development && flask run --host=0.0.0.0"
        ports:
            - "5000:5000"
    tails_stores_client:
        image: node:14-alpine3.14
        container_name: tails-stores-client-container
        volumes:
            - ./client:/app/client
        working_dir: /app/client
        command: sh -c "yarn install && yarn start"
        ports:
            - "3000:3000"
        env_file:
            - ./client/.env
